name: Laravel CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mongodb, pdo_sqlite
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env.testing') || copy('.env.example', '.env.testing');"

      - name: Install Composer Dependencies
        run: |
          if [ ! -f composer.lock ]; then
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          else
            composer update -q --no-ansi --no-interaction --prefer-dist
          fi
          
      - name: Install Node.js Dependencies & Build Frontend Assets
        run: |
          npm install
          npm run build

      - name: Generate Application Key
        run: php artisan key:generate --env=testing

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Database Migrations
        env:
          DB_URI: ${{ secrets.CONNECTION_STRING }}
        run: php artisan migrate --env=testing

      - name: Execute Tests (Unit and Feature tests)
        env:
          DB_URI: ${{ secrets.CONNECTION_STRING }}
        run: php artisan test --env=testing
